### ISSUE TITLE
CIL tutorial link not working

### ISSUE THREAD

**Issue by mahiuchun** [cil-project/cil#11]
As title.

**Comment by kerneis** [comment]
On Mon, May 19, 2014 at 08:45:52AM -0700, Xiaojun Ma wrote:

> Subject: CIL tutorial link not working (#11)
> https://github.com/kerneis/cil/issues/11

The author seems to have moved away from ETH Zurich, his webpage
is not available anymore.

Zach, is the pdf of the CIL tutorial now hosted elsewhere?

Best,
Gabriel

**Comment by kerneis** [comment]
I think I can host it directly from github. I'll look into that later today
or tomorrow.

Thanks for the heads-up.

Zach

**Comment by kerneis** [comment]
https://bitbucket.org/zanderso/cil-template/downloads/ciltut.pdf

Should work. Sorry for the delay.

Cheers,
Zach
