### ISSUE TITLE
cil.a is missing after installing via OPAM

### ISSUE THREAD

**Issue by soonhokong** [cil-project/cil#3]
I have installed cil-1.7.2 via opam-1.0.0 and have the following error when I tried to compile a package with CIL.

---

gcc: error: <HOME>/ocamlbrew/ocaml-4.00.1/.opam/system/lib/cil/cil.a: No such file or directory
File "caml_startup", line 1:
Error: Error during linking

**Comment by kerneis** [comment]
On Mon, Jul 22, 2013 at 03:06:34PM -0700, Soonho Kong wrote:

> I have installed cil-1.7.2 via opam-1.0.0 and have the following error when I
> tried to compile a package with CIL.

Thanks for the report.  This is a known issue, fixed in git repository.
I just need to make a release (probably later that week).

Gabriel

**Comment by soonhokong** [comment]
Thanks!!
